language: java

jdk:
  - openjdk8
  - openjdk10
  - openjdk11
  - oraclejdk9
  - oraclejdk11

install: echo "Don't install to local repo."

# Run tests, findbugs, pmd and friends
script: mvn -B clean verify
