name: CI

on:
  workflow_dispatch:  # No additional yaml keys are necessary
  pull_request:  # No additional yaml keys are necessary
  push:
    branches:
      - "master"
      - "main"

permissions: {}

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci-using-devenv:
    name: CI
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # https://github.com/actions/checkout/releases/tag/v7.0.0
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # https://github.com/cachix/install-nix-action/releases/tag/v31.10.6
        with:
          nix_path: nixpkgs=channel:nixos-25.11

      - name: Print nixpkgs version
        run: |
          nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

      - name: Install DevEnv
        env:
          LOCAL_DEVENV_REVISION: 55d2bb4a3cc710ba82cc8644f4419db3a802e1a4 # https://github.com/cachix/devenv/releases/tag/v2.0.6
        run: |
          nix profile add "github:cachix/devenv/${LOCAL_DEVENV_REVISION}" --accept-flake-config --option extra-substituters "https://devenv.cachix.org?trusted=true&priority=3"

      - name: Run devenv test
        run: |
          devenv test

      - name: Build, run tests, run static analysis
        shell: devenv shell bash -- -e {0}
        run: |
          mvn clean verify

  check-supported-jdks:
    needs: ci-using-devenv
    strategy:
      max-parallel: 1 # Avoid concurrency settings cancelling matrix builds
      matrix:
        jdk_version: [ 17, 21, 25 ]

    name: "JDK ${{ matrix.jdk_version }}"
    runs-on: ubuntu-latest # ubuntu-slim doesn't come with maven by default, and we want to avoid installing it in the workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # https://github.com/actions/checkout/releases/tag/v7.0.0
        with:
          persist-credentials: false

      - name: "Set up JDK ${{ matrix.jdk_version }}"
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # https://github.com/actions/setup-java/releases/tag/v5.5.0
        with:
          distribution: "temurin"
          java-version: ${{ matrix.jdk_version }}
          cache: "maven"
          cache-dependency-path: |
            **/pom.xml

      - name: Build, run tests, run static analysis
        shell: bash
        run: |
          mvn clean verify

# eof
