name: Release Changelog

on:
  workflow_dispatch:  # No additional yaml keys are necessary
  push:
    # Automatically create a GitHub Release entry when a tag that looks like a new release is pushed.
    # The tag pattern is defined in maven-release-plugin's settings in pom.xml authoritatively. The changelog
    # generator - git-cliff - just goes through all relevant tags, regardless of their name.
    tags:
      - 'v[0-9]+.*'

permissions: {}

concurrency:
  group: rel-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Create GitHub Release entry
    runs-on: ubuntu-slim
    permissions:
      contents: write # Needed by softprops/action-gh-release to create the GitHub Release entry
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
        with:
          persist-credentials: false
          #
          # Fetch full history, including tags, or otherwise the changelog generation will silently fail:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Nix
        uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # https://github.com/cachix/install-nix-action/releases/tag/v31.9.1
        with:
          nix_path: nixpkgs=channel:nixos-25.11

      - name: Print nixpkgs version
        run: |
          nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

      - name: Install devenv.sh
        run: |
          nix profile add github:cachix/devenv/v1.11.1 --accept-flake-config --option extra-substituters "https://devenv.cachix.org?trusted=true&priority=3"

      - name: Generate change list
        shell: devenv shell bash -- -e {0}
        run: |
          task release:changelog FILE=changes.md

      - name: Include the change list in summary
        shell: devenv shell bash -- -e {0}
        continue-on-error: true
        run: |
          echo -e "# Generated change list:\n\n----\n\n" >> "$GITHUB_STEP_SUMMARY"
          cat changes.md >> "$GITHUB_STEP_SUMMARY"

      - name: Create GitHub Release entry
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # https://github.com/softprops/action-gh-release/releases/tag/v2.5.0
        if: github.ref_type == 'tag'
        with:
          # Populate the release entry body with the notes we generated
          body_path: changes.md
          # A hooman still needs to push the butan
          draft: true

# eof
